### ISSUE TITLE
Add a new setting fragment.

### ISSUE THREAD

**Issue by Neelabh46** [opencodeiiita/OpenCode20-Collaborative-TheApp#10]
This should open when settings is clicked from the drop-down. Write text setting in the middle.

**Comment by aawizard** [comment]
@opencodebot claim

**Comment by aawizard** [comment]
i want to work on this issue

**Comment by NooBSagaR** [comment]
I want to work on it Please accept my request!

**Comment by lazyp4nd4** [comment]
i want to work on this task

**Comment by aawizard** [comment]
sir, in this, do I need to add the setting in the navigation bar or from the drop-down menu

**Comment by sandy9808** [comment]
claim

**Comment by aawizard** [comment]
sir please check my pr again
