### ISSUE TITLE
Add OpenCode logo in the navigation drawer.

### ISSUE THREAD

**Issue by Neelabh46** [opencodeiiita/OpenCode20-Collaborative-TheApp#3]

**Comment by animesh328** [comment]
Can I take this task???

**Comment by Neelabh46** [comment]
@animesh328 You have already been assigned 2 issues solve them first.

**Comment by aawizard** [comment]
can i work on this issue

**Comment by NooBSagaR** [comment]
I want to work on it! (Claim)

**Comment by animesh328** [comment]
> @animesh328 You have already been assigned 2 issues solve them first.

Sir,I have solved the previous issue.
Please assign me this issue

**Comment by starboi02** [comment]
sir can i work on this

**Comment by JLodha** [comment]
Claim

**Comment by sandy9808** [comment]
claim
