### ISSUE TITLE
Align OpenCode'20 logo to the left in Navigation Drawer.

### ISSUE THREAD

**Issue by MiKinshu** [opencodeiiita/OpenCode20-Collaborative-TheApp#52]
The logo is centrally placed rn, It should be aligned to left as is seen in many everyday apps.

**Comment by JLodha** [comment]
Claim

**Comment by Cybertron-Avneesh** [comment]
Claim

**Comment by Mridul20** [comment]
Sir I want to work on this project

**Comment by pradhuman1** [comment]
Claim

**Comment by sarthakm21** [comment]
Claim

**Comment by garvitchittora** [comment]
claim

**Comment by sarthakm21** [comment]
Sir it has been more than 2 days. Can I take it up?

**Comment by blaze-assault** [comment]
Claim .sir it has been inactive .i want to work on it
