### ISSUE TITLE
Add a parent and toolbar in settings activity

### ISSUE THREAD

**Issue by shiv07tiwari** [opencodeiiita/OpenCode20-Collaborative-TheApp#60]
1. Add a toolbar in settings activity
2. Add main activity as the parent of settings activity

**Comment by blaze-assault** [comment]
Claim

**Comment by Cybertron-Avneesh** [comment]
Claim

**Comment by infern018** [comment]
claim

**Comment by sarthakm21** [comment]
Claim

**Comment by blaze-assault** [comment]
@MiKinshu  sir please review

**Comment by blaze-assault** [comment]
@harchani-ritik @shiv07tiwari  @MiKinshu sir please review the pr .
