### ISSUE TITLE
When we rotate the device app always opens the home fragment

### ISSUE THREAD

**Issue by harchani-ritik** [opencodeiiita/OpenCode20-Collaborative-TheApp#63]

**Comment by harchani-ritik** [comment]
Steps to reproduce the bug-
1. Select any tab from navigation drawer instead of Home Tab.
2. Change the orientation (rotate the device) and you're back to Home Tab.

Resolve the bug, the app should stay in same fragment as selected prior to rotation.

PS: Understanding of Activity Lifecycle in Android is required.

**Comment by aawizard** [comment]
claim

**Comment by blaze-assault** [comment]
Claim

**Comment by blaze-assault** [comment]
@harchani-ritik  sir there is an error in app .it says default activity not found.i have forked and cloned this repo just now .please help sir.

**Comment by harchani-ritik** [comment]
@blaze-assault Yeah, resolved it , you can pull the changes now. Thanks for informing.
