### ISSUE TITLE
Star this repository.

### ISSUE THREAD

**Issue by Neelabh46** [opencodeiiita/OpenCode20-Collaborative-TheApp#7]

**Comment by JLodha** [comment]
Done http://prntscr.com/qp809p

**Comment by Cybertron-Avneesh** [comment]
See Screenshot here
https://prnt.sc/qp8dit

**Comment by aawizard** [comment]
done https://prnt.sc/qpabl3

**Comment by NooBSagaR** [comment]
https://imgur.com/a/GgFjIby done

**Comment by MiKinshu** [comment]
@NooBSagaR @aawizard @Cybertron-Avneesh @JLodha Please open a PR.

**Comment by lazyp4nd4** [comment]
![Screenshot (47)](https://user-images.githubusercontent.com/58784199/72661552-60b3dd00-3a01-11ea-8c27-2cbf7932519f.png)

**Comment by smcri** [comment]
Starred
![AppD](https://user-images.githubusercontent.com/16453560/72663622-bfd21b80-3a1a-11ea-8fc7-83ca99f1eb04.PNG)

**Comment by byte-king** [comment]
Starred
![image](https://user-images.githubusercontent.com/55686016/72663740-e2b0ff80-3a1b-11ea-9d80-665bbba99164.png)

**Comment by sandy9808** [comment]
![screenshot](https://user-images.githubusercontent.com/58395595/72664523-e432f580-3a24-11ea-90c6-1c8be445b3dc.png)
done my name:sandy9808

**Comment by ghost** [comment]
done http://prnt.sc/qpibt7

**Comment by Utkarshrock** [comment]
![Screenshot from 2020-01-18 23-22-36](https://user-images.githubusercontent.com/59891732/72668160-cfb52400-3a49-11ea-8008-9806eea5e695.png)
starred this repo

**Comment by roshnidesigns** [comment]
SS here
https://prntscr.com/qpjo9e

**Comment by deydaniel** [comment]
Starred
![Starred](https://user-images.githubusercontent.com/58394825/72681941-620f0380-3aee-11ea-8cf8-6fd16833796e.jpg)
