### ISSUE TITLE
Populate leaderboard fragment with Recycler View.

### ISSUE THREAD

**Issue by harchani-ritik** [opencodeiiita/OpenCode20-Collaborative-TheApp#82]
Initially put the placeholder (sample) data which would be updated later.

The list item will contain the following:
S.no.
Image Avatar
Participant Name
Github username
Total Points / No. of PR merged

**Comment by blaze-assault** [comment]
Claim

**Comment by Cybertron-Avneesh** [comment]
Claim

**Comment by sarthakm21** [comment]
Claim

**Comment by Cybertron-Avneesh** [comment]
can i work on it now.
