### ISSUE TITLE
Generate GridView in participants fragments with sample data. 

### ISSUE THREAD

**Issue by harchani-ritik** [opencodeiiita/OpenCode20-Collaborative-TheApp#83]
The card should contain Image, name and username of an individual.

**Comment by Cybertron-Avneesh** [comment]
Claim

**Comment by sarthakm21** [comment]
Claim.

**Comment by harchani-ritik** [comment]
@Cybertron-Avneesh Are you still working on this issue?

**Comment by Cybertron-Avneesh** [comment]
@harchani-ritik sir I tried to implement grid view but app is crashing when I select participant section from navigation drawer.

**Comment by blaze-assault** [comment]
Claim

**Comment by harchani-ritik** [comment]
@Cybertron-Avneesh Okay, so would you want some more time on it or should I assign someone else?
